package org.ddmac.openai;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.google.adk.models.*;
import com.google.genai.types.FunctionCall;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.BackpressureStrategy;
import io.reactivex.rxjava3.core.Flowable;
import org.ddmac.openai.dto.*;
import org.ddmac.openai.dto.OpenAIResponsesAPIRequest.Input;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.*;

/**
 * A reactive Large Language Model (LLM) adapter that integrates the OpenAI Responses API
 * with the Google Agent Development Kit (ADK).
 * <p>
 * This class extends {@link BaseLlm} to provide support for both synchronous and
 * asynchronous Server-Sent Events (SSE) streaming generation. It maps ADK {@link LlmRequest}
 * objects to OpenAI-compatible payloads and converts the resulting HTTP responses back into
 * a reactive {@link Flowable} stream of {@link LlmResponse} objects.
 */
public class OpenAIResponsesLlm extends BaseLlm {

    private static final Logger logger = LoggerFactory.getLogger(OpenAIResponsesLlm.class);

    private final HttpClient httpClient;
    private final ObjectMapper mapper;
    private final URI aiURI;
    private final String apiKey;

    /**
     * Constructs a new adapter for unauthenticated local servers (e.g., Ollama, LM Studio).
     * <p>
     * No Authorization header will be attached to the requests generated by this instance.
     *
     * @param model   The specific model identifier (e.g., "llama3").
     * @param baseUrl The base URL of the local server (e.g., "http://localhost:11434").
     */
    public OpenAIResponsesLlm(String model, String baseUrl) {
        this(model, baseUrl, null, false);
    }

    /**
     * Convenience constructor for standard OpenAI production usage.
     * <p>
     * This constructor automatically points to {@code https://api.openai.com} and securely
     * pulls the API key from the {@code OPENAI_API_KEY} environment variable.
     *
     * @param model The specific model identifier (e.g., "gpt-4o").
     * @throws IllegalArgumentException If the {@code OPENAI_API_KEY} environment variable is missing.
     */
    public OpenAIResponsesLlm(String model) {
        this(model, "https://api.openai.com", null, true);
    }

    /**
     * Constructs a new adapter for authenticated servers (e.g., Custom gateways, Enterprise vLLM).
     * <p>
     * If the provided apiKey is null or blank, the adapter will automatically
     * attempt to retrieve it from the {@code OPENAI_API_KEY} environment variable.
     *
     * @param model   The specific model identifier.
     * @param baseUrl The base URL of the OpenAI-compatible server.
     * @param apiKey  The explicit API key, or null to auto-load from the environment.
     * @throws IllegalArgumentException If auth is required but no key is provided or found in the environment.
     */
    public OpenAIResponsesLlm(String model, String baseUrl, String apiKey) {
        this(model, baseUrl, apiKey, true);
    }

    /**
     * Private master constructor to handle resolution, validation, and assignment.
     */
    private OpenAIResponsesLlm(String model, String baseUrl, String providedKey, boolean requireAuth) {
        super(model);

        String key = providedKey;

        if (requireAuth) {
            if (key == null || key.isBlank()) {
                key = System.getenv("OPENAI_API_KEY");
            }

            if (key == null || key.isBlank()) {
                throw new IllegalArgumentException((
                        "Missing API Key. Set OPENAI_API_KEY, pass it directly, or use the 2-parameter constructor for unauthenticated local models."
                ));
            }
        }

        this.httpClient = HttpClient.newHttpClient();
        this.mapper = new ObjectMapper();
        this.aiURI = URI.create(baseUrl + "/v1/responses");
        this.apiKey = key;
    }

    /**
     * Generates content using the underlying OpenAI-compatible model.
     *
     * @param llmRequest The standardized request from the ADK containing prompts, context, and configurations.
     * @param stream     If {@code true}, establishes an asynchronous SSE connection and emits partial chunks.
     *                   If {@code false}, blocks and emits a single complete response.
     * @return A {@link Flowable} stream of {@link LlmResponse} objects.
     */
    @Override
    public Flowable<LlmResponse> generateContent(LlmRequest llmRequest, boolean stream) {
        if (stream) {
            return streamResponse(llmRequest);
        } else {
            return singleResponse(llmRequest);
        }
    }

    /**
     * Handles asynchronous, Server-Sent Events (SSE) streaming generation.
     *
     * @param llmRequest The ADK request to process.
     * @return A reactive stream emitting partial {@link LlmResponse} chunks as they arrive.
     */
    private Flowable<LlmResponse> streamResponse(LlmRequest llmRequest) {
        return Flowable.create(emitter -> {
                    String reqBody = mapToOpenAIRequest(llmRequest, true).toJson();

                    HttpRequest.Builder httpRequestBuilder = HttpRequest.newBuilder()
                            .uri(aiURI)
                            .header("Content-Type", "application/json")
                            .POST(HttpRequest.BodyPublishers.ofString(reqBody));

                    if (apiKey != null && !apiKey.isBlank()) {
                        httpRequestBuilder.header("Authorization", "Bearer " + apiKey);
                    }

                    httpClient.sendAsync(
                            httpRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream()
                    ).whenComplete((res, throwable) -> {
                        if (throwable != null) {
                            emitter.onError(throwable);
                            return;
                        }

                        if (res.statusCode() != 200) {
                            emitter.onError(new RuntimeException("OpenAI API Error " + res.statusCode()));
                            return;
                        }

                        try (BufferedReader br = new BufferedReader(new InputStreamReader(res.body()))) {
                            String line;
                            String currentEvent = "";

                            while ((line = br.readLine()) != null) {
                                if (line.isEmpty()) continue;
                                if (!line.startsWith("event: ") && !line.startsWith("data: ")) {
                                    throw new RuntimeException("Error processing line: " + line);
                                }
                                if (line.startsWith("event: ")) {
                                    currentEvent = line.substring(7).trim();
                                }
                                if (line.startsWith("data: ")) {
                                    String jsonData = line.substring(6).trim();

                                    switch (currentEvent) {
                                        case "response.output_text.delta":
                                            try {
                                                LlmResponse chunk = parseStreamingResponse(jsonData);
                                                emitter.onNext(chunk);
                                            } catch (JsonProcessingException e) {
                                                emitter.onError(e);
                                                return;
                                            }
                                            break;
                                        case "response.completed":
                                            captureUsage(jsonData);
                                            emitter.onNext(
                                                    LlmResponse
                                                            .builder()
                                                            .turnComplete(true)
                                                            .partial(false)
                                                            .build()
                                            );
                                            emitter.onComplete();
                                            return;
                                        case "response.output_text.done":
                                            //check stuff
                                            break;
                                        case "error":
                                            emitter.onError(new RuntimeException("API response parsing failed: " + jsonData));
                                            return;
                                        default:
                                            break;
                                    }
                                }
                            }
                        } catch (IOException e) {
                            emitter.onError(e);
                            return;
                        }
                        emitter.onComplete();
                    });

                },
                BackpressureStrategy.BUFFER
        );
    }

    /**
     * Handles synchronous, single-turn content generation.
     *
     * @param llmRequest The ADK request to process.
     * @return A reactive stream emitting exactly one complete {@link LlmResponse}.
     */
    private Flowable<LlmResponse> singleResponse(LlmRequest llmRequest) {
        return Flowable.fromCallable(() -> {
            try {
                String reqBody = mapToOpenAIRequest(llmRequest, false).toJson();
                logger.info("Outbound: " + reqBody);
                HttpRequest.Builder httpRequestBuilder = HttpRequest.newBuilder()
                        .uri(aiURI)
                        .header("Content-Type", "application/json")
                        .POST(HttpRequest.BodyPublishers.ofString(reqBody));

                if (apiKey != null && !apiKey.isBlank()) {
                    httpRequestBuilder.header("Authorization", "Bearer " + apiKey);
                }

                HttpResponse<String> res = httpClient.send(
                        httpRequestBuilder.build(),
                        HttpResponse.BodyHandlers.ofString()
                );

                return parseSingleResponse(res.body());
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });
    }

    /**
     * Maps the ADK's standardized LlmRequest into the specific JSON shape required
     * by the OpenAI Responses API.
     *
     * @param llmRequest The incoming ADK request.
     * @param stream     Whether the payload should request a streaming response.
     * @return A constructed {@link OpenAIResponsesAPIRequest} ready for serialization.
     */
    private OpenAIResponsesAPIRequest<?> mapToOpenAIRequest(LlmRequest llmRequest, boolean stream) {
        OpenAIResponsesAPIRequest.Builder<?> builder = OpenAIResponsesAPIRequest.builder()
                .model(model())
                .stream(stream);

        if (stream) {
            String instructions = String.join("\n", llmRequest.getSystemInstructions());

            builder = builder.instructions(instructions);

            List<Input> inputs = llmRequest.contents().stream()
                    .map(content -> {
                        //get role and map model to assistant
                        String role = content.role().orElse("user").toLowerCase();
                        if (role.equals("model")) {
                            role = "assistant";
                        }

                        List<Content> contentList = content.parts().orElse(new ArrayList<>())
                                .stream().map(part -> new Content("input_text", part.text().orElse("")))
                                .toList();


                        return new Input(role, contentList);
                    })
                    .toList();

            builder = builder.input(inputs);
        } else {
            List<Input> inputs = llmRequest.contents().stream()
                    .map(content -> {
                        String role = content.role().orElse("user").toLowerCase();

                        if(role.equals("model")){
                            role = "assistant";
                        }
                        else if (role.equals("tool") || role.equals("function")){
                            role = "user";
                        }

                        List<Content> contentList = new ArrayList<>();
                        if (content.parts().isPresent()){
                            for (Part part: content.parts().get()){
                                if(part.text().isPresent()) {
                                    contentList.add(new Content("input_text", part.text().get()));
                                }
                                else if (part.functionResponse().isPresent()){
                                    try{
                                        Object responseData = part.functionResponse().get().response().orElseThrow();
                                        String resultJson = mapper.writeValueAsString(responseData);
                                        contentList.add(new Content("input_text","System Tool Output[" + part.functionResponse().get().name().orElseThrow() + "]: " + resultJson));
                                    } catch (Exception e) {
                                        contentList.add(new Content("input_text","Tool executed."));
                                    }
                                }
                                else if (part.functionCall().isPresent()) {
                                    contentList.add(new Content("input_text", "Action taken: Executed tool '" + part.functionCall().get().name().orElse("unknown") + "'"));
                                }
                            }
                        }
                        return new Input(role,contentList);
                    })
                    .filter(input -> !input.content().isEmpty())
                    .toList();
            builder = builder.input(inputs);
        }

        if (llmRequest.tools() != null && !llmRequest.tools().isEmpty()) {
            List<Tool> openAiTools = llmRequest.tools().values().stream()
                    .filter(t -> t.declaration() != null && t.declaration().isPresent())
                    .map(t -> {
                        try {
                            String rawJson = t.declaration().orElseThrow().toJson();
                            logger.debug("Tool found: {}", rawJson);
                            JsonNode root = mapper.readTree(rawJson);

                            lowercaseTypeFields(root);

                            Tool mappedTool = mapper.treeToValue(root, Tool.class);

                            return new Tool(
                                    "function",
                                    mappedTool.name(),
                                    mappedTool.description(),
                                    mappedTool.parameters(),
                                    null
                            );
                        } catch (Exception e) {
                            logger.error("Failed to map ADK tool to OpenAI format", e);
                            return null;
                        }
                    })
                    .filter(Objects::nonNull)
                    .toList();

            builder.tools(openAiTools);
        }


        return builder.build();
    }

    /**
     * Deserializes an SSE JSON chunk and converts it into a partial ADK response.
     *
     * @param json The JSON string received in the "data:" line of the SSE stream.
     * @return A partial {@link LlmResponse}.
     * @throws JsonProcessingException If the JSON cannot be parsed.
     */
    private LlmResponse parseStreamingResponse(String json) throws JsonProcessingException {
        OpenAIResponsesAPIStreamingResponse res = mapper.readValue(json, OpenAIResponsesAPIStreamingResponse.class);
        String text = res.delta() != null ? res.delta() : (res.text() != null ? res.text() : "");
        return buildLlmResponse(text, true);
    }

    /**
     * Deserializes a complete API JSON response and converts it into a final ADK response.
     *
     * @param json The raw JSON string returned by the non-streaming endpoint.
     * @return A complete, non-partial {@link LlmResponse}.
     * @throws JsonProcessingException If the JSON cannot be parsed.
     */
    private LlmResponse parseSingleResponse(String json) throws JsonProcessingException {
        OpenAIResponsesAPISingleResponse res = mapper.readValue(json, OpenAIResponsesAPISingleResponse.class);

        for(OpenAIResponsesAPISingleResponse.Output out: res.output()){
            if(out.type().equals("function_call")){
                Map<String,Object> argsMap = new HashMap<>();
                try{
                    if(out.arguments() != null && !out.arguments().isBlank()) {
                        argsMap = mapper.readValue(out.arguments(),
                                new TypeReference<>() { });

                    }
                } catch (Exception e) {
                    logger.error("Failed to parse tool args for tool: {}", out.name(), e);
                }

                Part toolPart = Part.builder()
                        .functionCall(
                            FunctionCall.builder()
                                .id(out.callId())
                                .name(out.name())
                                .args(argsMap)
                                .build()
                        ).build();

                return LlmResponse.builder()
                        .content(
                                com.google.genai.types.Content.builder()
                                        .role("model")
                                        .parts(List.of(toolPart))
                                        .build()
                        )
                        .turnComplete(false)
                        .build();
            }

            if(out.type().equals("message") && out.content() != null){
                StringBuilder sb = new StringBuilder();

                out.content().stream()
                        .filter(c -> c.text() != null)
                        .forEach(c -> sb.append(c.text()));

                return buildLlmResponse(sb.toString(), false);
            }
        }
        return buildLlmResponse("",false);
    }

    /**
     * Constructs the final ADK {@link LlmResponse} object, setting the appropriate
     * stream management flags.
     *
     * @param text      The text generated by the model.
     * @param isPartial {@code true} if this is an incomplete chunk from a stream; {@code false} otherwise.
     * @return The configured {@link LlmResponse}.
     */
    private LlmResponse buildLlmResponse(String text, boolean isPartial) {
        Part part = Part.builder().text(text).build();
        com.google.genai.types.Content content = com.google.genai.types.Content.builder()
                .role("assistant")
                .parts(List.of(part))
                .build();

        return LlmResponse.builder().content(content)
                .partial(isPartial)
                .turnComplete(!isPartial)
                .build();
    }

    /**
     * Extracts token usage statistics from the final completion event of a stream
     * and logs them for telemetry purposes.
     *
     * @param json The JSON payload of the "response.completed" event.
     */
    private void captureUsage(String json) {
        try {
            OpenAIResponsesAPIStreamingResponse res = mapper.readValue(json, OpenAIResponsesAPIStreamingResponse.class);
            StringBuilder sb = new StringBuilder();
            if (res.response() != null && res.response().usage() != null) {
                sb.append("Token Usage\n")
                        .append(String.format("\tInput Tokens: %d\n", res.response().usage().inputTokens()))
                        .append(String.format("\tOutput Tokens: %d\n", res.response().usage().outputTokens()))
                        .append(String.format("\tTotal Tokens: %d\n", res.response().usage().totalTokens()));
                logger.warn(sb.toString());
            }
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Puts all values to lowercase for OpenAI schema validation.
     *
     * @param node a Jackson JsonNode
     */
    private void lowercaseTypeFields(JsonNode node) {
        if (node.isObject()) {
            ObjectNode obj = (ObjectNode) node;
            if (obj.has("type") && obj.get("type").isTextual()) {
                obj.put("type", obj.get("type").asText().toLowerCase());
            }
            obj.elements().forEachRemaining(this::lowercaseTypeFields);
        } else if (node.isArray()) {
            node.elements().forEachRemaining(this::lowercaseTypeFields);
        }
    }

    @Override
    public BaseLlmConnection connect(LlmRequest llmRequest) {
        throw new UnsupportedOperationException("Bidirectional live streaming is not supported by this provider.");
    }
}
