package org.ddmac.openai.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jspecify.annotations.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Represents a specific block of content within an OpenAI message.
 * <p>
 * This immutable data transfer object (DTO) maps to the content array structure
 * expected by OpenAI-compatible endpoints. A single message or prompt can consist
 * of multiple {@code Content} blocks (e.g., a mix of text and image inputs).
 *
 * @param type The type of the content block (e.g., {@code "text"} or {@code "input_text"}).
 * @param text The actual string content, such as a user prompt or a model's response chunk.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Content(
        @JsonProperty("type") String type,
        @JsonProperty("text") String text
) {
    private static final Logger logger = LoggerFactory.getLogger(Content.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    /**
     * Serializes this content block into a formatted JSON string.
     * <p>
     * If an error occurs during Jackson processing, the error is logged and an
     * empty JSON object is returned to prevent application crashes.
     *
     * @return A JSON string representation of this object, or {@code "{}"} if serialization fails.
     */
    public String toJson() {
        try {
            return MAPPER.writeValueAsString(this);
        } catch (JsonProcessingException e) {
            logger.error("Failed to serialize", e);
            return "{}";
        }
    }

    /**
     * Returns the string representation of this content block.
     *
     * @return The JSON string generated by {@link #toJson()}.
     */
    @Override
    public @NonNull String toString() {
        return toJson();
    }

}
