package org.ddmac.openai.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jspecify.annotations.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Represents a single Server-Sent Event (SSE) chunk returned during a streaming
 * generation from the OpenAI Responses API.
 * <p>
 * This immutable data transfer object (DTO) captures real-time data as it arrives
 * over the network. Depending on the SSE event type (e.g., "response.output_text.delta"
 * or "response.completed"), certain fields like {@code delta} or {@code response}
 * will be populated while others remain null.
 *
 * @param delta    The incremental text generated in this specific chunk. Usually present
 * during "delta" events.
 * @param text     The cumulative text or specific text payload, depending on the event.
 * @param response The final completion metadata, including token usage. This is typically
 * only populated during the final "response.completed" event.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record OpenAIResponsesAPIStreamingResponse(
        @JsonProperty("delta") String delta,
        @JsonProperty("text") String text,
        @JsonProperty("response") ResponseData response,

        @JsonAlias({"name","tool_name","function_name"})
        @JsonProperty("name") String name,

        @JsonAlias({"call_id","tool_id","id","function_id"})
        @JsonProperty("call_id") String callId,

        @JsonProperty("item") NestedToolItem item,
        @JsonProperty("function") NestedToolItem function
) {

    private static final Logger logger = LoggerFactory.getLogger(OpenAIResponsesAPIStreamingResponse.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    /**
     * Contains metadata, status, and final usage statistics sent when a stream completes.
     *
     * @param id         The unique identifier for the response payload.
     * @param status     The final status of the generation (e.g., "completed").
     * @param usage      The token consumption statistics for the entire streaming turn.
     * @param outputText The complete, concatenated text generated by the model over the stream.
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record ResponseData(
            String id,
            String status,
            @JsonProperty("usage") Usage usage,
            @JsonProperty("output_text") String outputText
    ) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record NestedToolItem(
            @JsonAlias({"name","tool_name","function_name"})
            @JsonProperty("name") String name,

            @JsonAlias({"call_id","tool_id","id","function_id"})
            @JsonProperty("call_id") String callId

    ){}


    /**
     * Helper method to seamlessly extract the tool name regardless of how the server nested it.
     */
    public String extractToolName() {
        if (name != null) return name;
        if (item != null && item.name() != null) return item.name();
        if (function != null && function.name() != null) return function.name();
        return null;
    }

    /**
     * Helper method to seamlessly extract the tool ID regardless of how the server nested it.
     */
    public String extractCallId() {
        if (callId != null) return callId;
        if (item != null && item.callId() != null) return item.callId();
        if (function != null && function.callId() != null) return function.callId();
        return null;
    }

    /**
     * Serializes this stream chunk into a valid JSON string.
     * <p>
     * If an error occurs during Jackson processing, the error is logged and an
     * empty JSON object is returned to prevent stream interruption.
     *
     * @return A JSON string representation of this object, or {@code "{}"} if serialization fails.
     */
    public String toJson() {
        try {
            return MAPPER.writeValueAsString(this);
        } catch (JsonProcessingException e) {
            logger.error("Failed to serialize response", e);
            return "{}";
        }
    }

    /**
     * Returns the string representation of this stream chunk.
     *
     * @return The JSON string generated by {@link #toJson()}.
     */
    @Override
    public @NonNull String toString() {
        return toJson();
    }

}
