package org.ddmac.openai.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jspecify.annotations.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

/**
 * Represents the complete, non-streaming JSON response returned by the OpenAI Responses API.
 * <p>
 * This immutable data transfer object (DTO) captures the final output generated by the model
 * when a synchronous (non-streaming) request is fulfilled. It contains the generated messages
 * as well as the token usage statistics for the turn.
 *
 * @param output A list of generated outputs or choices provided by the model.
 * @param usage  The token consumption statistics for this request.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record OpenAIResponsesAPISingleResponse(
        @JsonProperty("output")
        List<Output> output,
        Usage usage
) {

    private static final Logger logger = LoggerFactory.getLogger(OpenAIResponsesAPISingleResponse.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();


    /**
     * Represents a single generated message or choice within the API response.
     *
     * @param content A list of {@link Content} blocks comprising the actual generated text or data.
     * @param role    The role of the author of this output (typically "assistant").
     * @param type    The specific type of the output (e.g., "message" or "text").
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record Output(
            @JsonProperty("content") List<Content> content,
            @JsonProperty("role") String role,
            @JsonProperty("type") String type
    ) {
    }

    /**
     * Serializes this response record into a valid JSON string.
     * <p>
     * If an error occurs during Jackson processing, the error is logged and an
     * empty JSON object is returned to prevent application crashes during deserialization.
     *
     * @return A JSON string representation of this object, or {@code "{}"} if serialization fails.
     */
    public String toJson() {
        try {
            return MAPPER.writeValueAsString(this);
        } catch (JsonProcessingException e) {
            logger.error("Failed to serialize response", e);
            return "{}";
        }
    }

    /**
     * Returns the string representation of this response record.
     *
     * @return The JSON string generated by {@link #toJson()}.
     */
    @Override
    public @NonNull String toString() {
        return toJson();
    }
}
