package org.ddmac.openai.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jspecify.annotations.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Represents the token usage statistics for an OpenAI API completion.
 * <p>
 * This immutable data transfer object (DTO) captures the number of input, output,
 * and total tokens consumed during a model's generation turn. It is primarily used
 * for telemetry, logging, and cost tracking.
 *
 * @param inputTokens  The number of tokens processed from the user's prompt and context.
 * @param outputTokens The number of tokens generated by the model in its response.
 * @param totalTokens  The combined total of both input and output tokens.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Usage(
        @JsonProperty("input_tokens") int inputTokens,
        @JsonProperty("output_tokens") int outputTokens,
        @JsonProperty("total_tokens") int totalTokens
) {

    private static final Logger logger = LoggerFactory.getLogger(Usage.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    /**
     * Serializes this usage record into a formatted JSON string.
     * <p>
     * If an error occurs during Jackson processing, the error is logged and an
     * empty JSON object is returned to prevent stream interruption.
     *
     * @return A JSON string representation of this object, or {@code "{}"} if serialization fails.
     */
    public String toJson() {
        try {
            return MAPPER.writeValueAsString(this);
        } catch (JsonProcessingException e) {
            logger.error("Failed to serialize", e);
            return "{}";
        }
    }

    /**
     * Returns the string representation of this usage record.
     *
     * @return The JSON string generated by {@link #toJson()}.
     */
    @Override
    public @NonNull String toString() {
        return toJson();
    }
}
